name: Standup Bot

on:
  schedule:
    - cron: '0 14 * * 1-5' # Runs at 14:00 UTC, Monday to Friday

jobs:
  send_standup_message:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: |
        gem install bundler
        gem install slack-ruby-client

    - name: Run standup bot
      run: ruby standup_bot.rb
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
