version: '3.8'

services:
  manim-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media/videos:/app/media/videos
      - .:/app  # This line maps the current directory to /app in the container
    entrypoint: ["manim", "-p", "-ql", "morse.py", "MorseCode"]
